let canvas = document.querySelector("canvas");
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let ctx = canvas.getContext("2d");

//background
//sky
let sky = canvas.getContext("2d");
sky.beginPath();
sky.rect(0, 0, 2000, 1000);
sky.fillStyle = "midnightBlue";
sky.fill();
sky.closePath();
//grass
let grass = canvas.getContext("2d");
grass.beginPath();
grass.rect(0, 500, 2000, 500);
grass.fillStyle = "seaGreen";
grass.fill();
grass.closePath();
//weather
//stars
let stars = canvas.getContext("2d");
stars.beginPath();
stars.arc(40, 30, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(30, 130, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(150, 50, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(850, 130, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(750, 30, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(370, 60, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(550, 80, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(420, 145, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(200, 115, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(300, 190, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(90, 225, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(190, 287, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(300, 367, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(60, 407, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(900, 457, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(810, 425, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(855, 320, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
stars.beginPath();
stars.arc(760, 230, 1, 0, Math.PI * 2, true);
stars.fillStyle = "yellow";
stars.fill();
stars.closePath();
//
//house
let house = canvas.getContext("2d");
house.beginPath();
house.rect(370, 260, 400, 350);
house.fillStyle = "lightSalmon";
house.fill();
house.closePath();
//
//smoke
let smoke = canvas.getContext("2d");
smoke.beginPath();
smoke.arc(693, 150, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(685, 135, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(695, 125, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(680, 115, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(690, 100, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(685, 80, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(675, 60, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(685, 40, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(680, 20, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
smoke.beginPath();
smoke.arc(670, 10, 15, 0, Math.PI * 2, false);
smoke.fillStyle = "grey";
smoke.fill();
smoke.closePath();
//
//house chimmney
let chimney = canvas.getContext("2d");
chimney.beginPath();
chimney.rect(675, 160, 35, 70);
chimney.fillStyle = "black";
chimney.fill();
chimney.closePath();
//
//houseRoof
let houseRoof = canvas.getContext("2d");
houseRoof.beginPath();
houseRoof.moveTo(780, 265);
houseRoof.lineTo(360, 265);
houseRoof.lineTo(565, 140);
houseRoof.fillStyle = "darkRed";
houseRoof.fill();
houseRoof.closePath();
//

//
//door
let door = canvas.getContext("2d");
door.beginPath();
door.rect(430, 470, 80, 140);
door.fillStyle = "darkGoldenRod";
door.fill();
door.closePath();
//
//doorWindow
let doorWindow = canvas.getContext("2d");
doorWindow.beginPath();
doorWindow.ellipse(470, 500, 15, 25, Math.PI / 2, 0, Math.PI * 2);
doorWindow.fillStyle = "lightYellow";
doorWindow.fill();
doorWindow.lineWidth = 3;
doorWindow.strokeStyle = "black";
doorWindow.stroke();
doorWindow.closePath();
//door window pattern
doorWindow.beginPath();
doorWindow.moveTo(495, 500);
doorWindow.lineTo(445, 500);
doorWindow.lineWidth = 3;
doorWindow.strokeStyle = "black";
doorWindow.stroke();
doorWindow.closePath();
doorWindow.beginPath();
doorWindow.moveTo(470, 485);
doorWindow.lineTo(470, 515);
doorWindow.lineWidth = 3;
doorWindow.strokeStyle = "black";
doorWindow.stroke();
doorWindow.closePath();

//wreath
let wreath = canvas.getContext("2d");
wreath.beginPath();
wreath.arc(470, 525, 8, 0, Math.PI * 2, true);
wreath.lineWidth = "4";
wreath.strokeStyle = "green";
wreath.stroke();
wreath.closePath();
wreath.beginPath();
wreath.arc(470, 535, 3, 0, Math.PI * 2, true);
wreath.fillStyle = "red";
wreath.fill();
wreath.closePath();
wreath.beginPath();
wreath.moveTo(470, 535);
wreath.lineTo(465, 540);
wreath.moveTo(470, 535);
wreath.lineTo(475, 540);
wreath.lineWidth = 3;
wreath.strokeStyle = "red";
wreath.stroke();
wreath.closePath();

//doorknob
let doorKnob = canvas.getContext("2d");
doorKnob.beginPath();
doorKnob.arc(445, 545, 5, 0, Math.PI * 2, true);
doorKnob.fillStyle = "black";
doorKnob.fill();
doorKnob.closePath();

//window1
let window1 = canvas.getContext("2d");
window1.beginPath();
window1.rect(430, 310, 80, 80);
window1.fillStyle = "lightYellow";
window1.fill();
window1.lineWidth = 3;
window1.strokeStyle = "black";
window1.stroke();
window1.closePath();
//curtain for window one
window1.beginPath();
window1.rect(432, 311, 76, 75);
window1.fillStyle = "purple";
window1.fill();
window1.closePath();
//
//window one pattern
window1.beginPath();
window1.moveTo(430, 352);
window1.lineTo(510, 352);
window1.lineWidth = 3;
window1.strokeStyle = "black";
window1.stroke();
window1.closePath();
window1.beginPath();
window1.moveTo(470, 310);
window1.lineTo(470, 390);
window1.lineWidth = 3;
window1.strokeStyle = "black";
window1.stroke();
window1.closePath();
//underWindow
window1.beginPath();
window1.rect(425, 390, 90, 10);
window1.fillStyle = "grey";
window1.fill();
window1.lineWidth = 3;
window1.strokeStyle = "black";
window1.stroke();
window1.closePath();
//
//snow window 1
let snow = canvas.getContext("2d");
snow.beginPath();
snow.arc(430, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(435, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(440, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(445, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(450, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(455, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(460, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(465, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(470, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(475, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(480, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(485, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(490, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(495, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(500, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(505, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(510, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
//
//
//window2
let window2 = canvas.getContext("2d");
window2.beginPath();
window2.rect(610, 310, 80, 80);
window2.fillStyle = "lightYellow";
window2.fill();
window2.lineWidth = 3;
window2.strokeStyle = "black";
window2.stroke();
window2.closePath();
//curtain for window 2
window2.beginPath();
window2.rect(612, 311, 76, 75);
window2.fillStyle = "purple";
window2.fill();
window2.closePath();
//
//window 2 pattern
window2.beginPath();
window2.moveTo(610, 352);
window2.lineTo(690, 352);
window2.lineWidth = 3;
window2.strokeStyle = "black";
window2.stroke();
window2.closePath();
window2.beginPath();
window2.moveTo(650, 310);
window2.lineTo(650, 390);
window2.lineWidth = 3;
window2.strokeStyle = "black";
window2.stroke();
window2.closePath();
//underWindow2
window2.beginPath();
window2.rect(605, 390, 90, 10);
window2.fillStyle = "grey";
window2.fill();
window2.lineWidth = 3;
window2.strokeStyle = "black";
window2.stroke();
window2.closePath();
//
//snow window 2
snow.beginPath();
snow.arc(610, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(615, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(620, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(625, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(630, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(635, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(640, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(645, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(650, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(655, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(660, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(665, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(670, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(675, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(680, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(685, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(690, 387, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
//
//
//window3
let window3 = canvas.getContext("2d");
window3.beginPath();
window3.rect(610, 470, 80, 80);
window3.fillStyle = "lightYellow";
window3.fill();
window3.lineWidth = 3;
window3.strokeStyle = "black";
window3.stroke();
window3.closePath();
//curtain for window3
window3.beginPath();
window3.rect(612, 471, 76, 75);
window3.fillStyle = "purple";
window3.fill();
window3.closePath();
//
//window 3 pattern
window3.beginPath();
window3.moveTo(610, 510);
window3.lineTo(690, 510);
window3.lineWidth = 3;
window3.strokeStyle = "black";
window3.stroke();
window3.closePath();
window3.beginPath();
window3.moveTo(650, 550);
window3.lineTo(650, 470);
window3.lineWidth = 3;
window3.strokeStyle = "black";
window3.stroke();
window3.closePath();
//underWindow3
window3.beginPath();
window3.rect(605, 550, 90, 10);
window3.fillStyle = "grey";
window3.fill();
window3.lineWidth = 3;
window3.strokeStyle = "black";
window3.stroke();
window3.closePath();
//
//snow window 3
snow.beginPath();
snow.arc(610, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(615, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(620, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(625, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(630, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(635, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(640, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(645, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(650, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(655, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(660, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(665, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(670, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(675, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(680, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(685, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(690, 548, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();

//tree
//trunk
let trunk = canvas.getContext("2d");
trunk.beginPath();
trunk.rect(0, 670, 50, 260);
trunk.fillStyle = "saddleBrown";
trunk.fill();
trunk.closePath();

let xmasTree = canvas.getContext("2d");

xmasTree.beginPath();
xmasTree.moveTo(200, 765);
xmasTree.lineTo(0, 765);
xmasTree.lineTo(0, 620);
xmasTree.fillStyle = "darkGreen";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(150, 680);
xmasTree.lineTo(0, 535);
xmasTree.lineTo(0, 680);
xmasTree.fillStyle = "darkGreen";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(100, 600);
xmasTree.lineTo(0, 485);
xmasTree.lineTo(0, 600);
xmasTree.fillStyle = "darkGreen";
xmasTree.fill();
xmasTree.closePath();

//star

xmasTree.beginPath();
xmasTree.moveTo(-5, 485);
xmasTree.lineTo(40, 510);
xmasTree.lineTo(20, 460);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(0, 440);
xmasTree.lineTo(0, 480);
xmasTree.lineTo(55, 440);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(0, 400);
xmasTree.lineTo(0, 440);
xmasTree.lineTo(15, 440);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();

//decor

xmasTree.beginPath();
xmasTree.moveTo(65, 560);
xmasTree.bezierCurveTo(20, 590, 40, 580, 0, 600);
xmasTree.lineWidth = 5;
xmasTree.strokeStyle = "silver";
xmasTree.stroke();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(90, 620);
xmasTree.bezierCurveTo(30, 660, 40, 650, 0, 670);
xmasTree.lineWidth = 5;
xmasTree.strokeStyle = "silver";
xmasTree.stroke();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.moveTo(110, 700);
xmasTree.bezierCurveTo(40, 730, 45, 720, 0, 730);
xmasTree.lineWidth = 5;
xmasTree.strokeStyle = "silver";
xmasTree.stroke();
xmasTree.closePath();

//baubles
xmasTree.beginPath();
xmasTree.arc(195, 768, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(150, 686, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(100, 605, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "yellow";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(10, 525, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "red";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(30, 565, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "orange";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(50, 605, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "cyan";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(15, 630, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "purple";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(100, 655, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "silver";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(65, 675, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "orange";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(25, 690, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "red";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(15, 750, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "purple";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(135, 745, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "orange";
xmasTree.fill();
xmasTree.closePath();
xmasTree.beginPath();
xmasTree.arc(70, 735, 5, 0, Math.PI * 2, true);
xmasTree.fillStyle = "cyan";
xmasTree.fill();
xmasTree.closePath();

//roof snow
snow.beginPath();
snow.arc(365, 260, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(370, 256, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(375, 252, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(380, 248, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(385, 245, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(390, 241, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(395, 238, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(400, 235, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(405, 232, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(410, 229, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(415, 226, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(420, 223, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(425, 220, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(430, 217, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(435, 214, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(440, 211, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(445, 208, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(450, 205, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(455, 202, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(460, 199, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(465, 196, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(470, 193, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(475, 190, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(480, 187, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(485, 184, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(490, 181, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(495, 178, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(500, 175, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(505, 172, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(510, 169, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(515, 166, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(520, 163, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(525, 160, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(530, 157, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(535, 154, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(540, 151, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(545, 148, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(550, 145, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(555, 142, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(560, 139, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
//
//
snow.beginPath();
snow.arc(565, 139, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(570, 142, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(575, 145, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(580, 148, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(585, 151, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(590, 154, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(595, 157, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(600, 160, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(605, 163, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(610, 166, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(615, 169, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(620, 172, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(625, 175, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(630, 178, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(635, 181, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(640, 184, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(645, 187, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(650, 190, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(655, 193, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(660, 196, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(665, 199, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(670, 202, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(675, 205, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(680, 208, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(685, 211, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(690, 214, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(695, 217, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(700, 220, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(705, 223, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(710, 226, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(715, 229, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(720, 232, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(725, 235, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(730, 238, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(735, 241, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(740, 244, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(745, 247, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(750, 250, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(755, 253, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(760, 256, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(765, 259, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.beginPath();
snow.arc(770, 262, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();
snow.beginPath();
snow.arc(775, 265, 5, 0, Math.PI * 2, true);
snow.fillStyle = "white";
snow.fill();
snow.closePath();

//
//word
words = canvas.getContext("2d");
words.beginPath();
words.font = "35px Comic Sans MS";
words.fillStyle = "white";
words.fillText("Happy Holidays", 510, 700);
words.closePath();
words.beginPath();
words.font = "35px Comic Sans MS";
words.fillStyle = "white";
words.fillText("Everyone", 560, 760);
words.closePath();

//
//snowman
//body
snowman = canvas.getContext("2d");
snowman.beginPath();
snowman.arc(190, 530, 50, 0, Math.PI * 2, true);
snowman.fillStyle = "white";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(190, 470, 40, 0, Math.PI * 2, true);
snowman.fillStyle = "white";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(190, 420, 30, 0, Math.PI * 2, true);
snowman.fillStyle = "white";
snowman.fill();
snowman.closePath();

//hat
snowman.beginPath();
snowman.rect(165, 383, 50, 10);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.rect(177, 360, 25, 30);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();

//eyes
snowman.beginPath();
snowman.arc(181, 405, 4, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(198, 405, 4, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
//nose
snowman.beginPath();
snowman.moveTo(190, 425);
snowman.lineTo(195, 415);
snowman.lineTo(185, 415);
snowman.fillStyle = "orange";
snowman.fill();
snowman.closePath();
//mouth
snowman.beginPath();
snowman.arc(173, 420, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(176, 428, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(183, 434, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(194, 434, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(203, 428, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(208, 420, 3, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();

//arms
snowman.beginPath();
snowman.moveTo(230, 460);
snowman.lineTo(280, 440);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(280, 460);
snowman.lineTo(255, 450);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(265, 423);
snowman.lineTo(255, 450);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(150, 460);
snowman.lineTo(110, 440);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(110, 460);
snowman.lineTo(130, 450);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(125, 425);
snowman.lineTo(130, 450);
snowman.strokeStyle = "saddleBrown";
snowman.stroke();
snowman.closePath();

//buttons
snowman.beginPath();
snowman.arc(190, 460, 5, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(190, 500, 5, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();
snowman.beginPath();
snowman.arc(190, 540, 5, 0, Math.PI * 2, true);
snowman.fillStyle = "black";
snowman.fill();
snowman.closePath();

//scarf
snowman.beginPath();
snowman.moveTo(218, 438);
snowman.bezierCurveTo(210, 450, 160, 450, 165, 438);
snowman.lineWidth = 8;
snowman.strokeStyle = "purple";
snowman.stroke();
snowman.closePath();
snowman.beginPath();
snowman.moveTo(217, 440);
snowman.bezierCurveTo(210, 450, 225, 450, 220, 480);
snowman.lineWidth = 8;
snowman.strokeStyle = "purple";
snowman.stroke();
snowman.closePath();
