let canvas = document.querySelector("canvas");
let ctx = canvas.getContext("2d");

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

//background
ctx.beginPath();
ctx.rect(0, 0, 2000, 1000);
ctx.fillStyle = "beige";
ctx.fill();
ctx.closePath();

//cake
ctx.beginPath();
ctx.ellipse(900, 645, 100, 50, Math.PI / 1, 0, Math.PI * 2);
ctx.fillStyle = "chocolate";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.rect(800, 500, 200, 150);
ctx.fillStyle = "chocolate";
ctx.fill();
ctx.closePath();

//cake outline
ctx.beginPath();
ctx.moveTo(800, 500);
ctx.lineTo(800, 650);
ctx.strokeStyle = "black";
ctx.lineWidth = 2;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(1000, 500);
ctx.lineTo(1000, 650);
ctx.strokeStyle = "black";
ctx.lineWidth = 2;
ctx.stroke();
ctx.closePath();

//icing
ctx.beginPath();
ctx.ellipse(814, 522, 22, 15, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(843, 543, 22, 18, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(880, 553, 22, 21, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(922, 553, 22, 21, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(959, 540, 22, 18, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(988, 520, 22, 13, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "pink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//icing top
ctx.beginPath();
ctx.ellipse(900, 500, 100, 55, Math.PI / 1, 0, Math.PI * 2);
ctx.fillStyle = "lightPink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//jam and cream
ctx.beginPath();
ctx.line;
ctx.lineWidth = 9;
ctx.lineCap = "round";
ctx.strokeStyle = "red";
ctx.bezierCurveTo(803, 585, 870, 645, 995, 590);
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.line;
ctx.lineWidth = 9;
ctx.lineCap = "round";
ctx.strokeStyle = "peachPuff";
ctx.bezierCurveTo(802, 594, 880, 650, 995, 598);
ctx.stroke();
ctx.closePath();

// candles
//candle 1
ctx.beginPath();
ctx.rect(820, 420, 15, 80);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//pattern
ctx.beginPath();
ctx.moveTo(834, 422);
ctx.lineTo(821, 440);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(834, 447);
ctx.lineTo(821, 467);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(834, 475);
ctx.lineTo(821, 493);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
//flame
ctx.beginPath();
ctx.ellipse(827, 404, 14, 5.5, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(827, 409, 9, 3, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//candle 2
ctx.beginPath();
ctx.rect(860, 390, 15, 80);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//pattern
ctx.beginPath();
ctx.moveTo(874, 392);
ctx.lineTo(861, 410);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(874, 417);
ctx.lineTo(861, 435);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(874, 445);
ctx.lineTo(861, 463);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
//flame
ctx.beginPath();
ctx.ellipse(867, 374, 14, 5.5, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(867, 378, 9, 3, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//candle 3
ctx.beginPath();
ctx.rect(890, 450, 15, 80);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//pattern
ctx.beginPath();
ctx.moveTo(903, 452);
ctx.lineTo(891, 475);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(903, 479);
ctx.lineTo(891, 500);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(903, 510);
ctx.lineTo(891, 527);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
//flame
ctx.beginPath();
ctx.ellipse(897, 433, 14, 5.5, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(897, 437, 9, 3, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//candle 4
ctx.beginPath();
ctx.rect(920, 390, 15, 80);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//pattern
ctx.beginPath();
ctx.moveTo(933, 392);
ctx.lineTo(920, 410);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(933, 417);
ctx.lineTo(920, 435);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(933, 445);
ctx.lineTo(920, 463);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
//flame
ctx.beginPath();
ctx.ellipse(927, 374, 14, 5.5, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(927, 378, 9, 3, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//candle 5
ctx.beginPath();
ctx.rect(960, 430, 15, 80);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//pattern
ctx.beginPath();
ctx.moveTo(974, 430);
ctx.lineTo(960, 450);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(974, 460);
ctx.lineTo(960, 480);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(974, 490);
ctx.lineTo(961, 508);
ctx.strokeStyle = "blue";
ctx.lineCap = "round";
ctx.lineWidth = 3;
ctx.stroke();
ctx.closePath();
//flame
ctx.beginPath();
ctx.ellipse(967, 414, 14, 5.5, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(967, 418, 9, 3, Math.PI / 2, 0, Math.PI * 2);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//balloons
//balloon 1
ctx.beginPath();
ctx.ellipse(150, 290, 100, 55, Math.PI / 2.2, 0, Math.PI * 2);
ctx.fillStyle = "springGreen";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//string
ctx.beginPath();
ctx.moveTo(170, 405);
ctx.lineTo(240, 700);
ctx.lineWidth = 4;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(168, 388);
ctx.lineTo(160, 410);
ctx.lineTo(185, 400);
ctx.lineTo(168, 388);
ctx.fillStyle = "springGreen";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//balloon2
ctx.beginPath();
ctx.ellipse(255, 290, 100, 55, Math.PI / -2.1, 0, Math.PI * 2);
ctx.fillStyle = "purple";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//string
ctx.beginPath();
ctx.moveTo(245, 395);
ctx.lineTo(240, 700);
ctx.lineWidth = 4;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(245, 388);
ctx.lineTo(230, 410);
ctx.lineTo(260, 410);
ctx.lineTo(245, 388);
ctx.fillStyle = "purple";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//balloon 3
ctx.beginPath();
ctx.ellipse(360, 300, 100, 55, Math.PI / -2.3, 0, Math.PI * 2);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//string
ctx.beginPath();
ctx.moveTo(340, 400);
ctx.lineTo(240, 700);
ctx.lineWidth = 4;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(345, 390);
ctx.lineTo(320, 410);
ctx.lineTo(355, 420);
ctx.lineTo(345, 390);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//smiley face
//hat
ctx.beginPath();
ctx.moveTo(1700, 350);
ctx.lineTo(1510, 525);
ctx.lineTo(1670, 600);
ctx.lineTo(1700, 350);
ctx.fillStyle = "white";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//spots
ctx.beginPath();
ctx.arc(1670, 410, 15, 0, Math.PI * 2, false);
ctx.fillStyle = "red";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(1660, 470, 15, 0, Math.PI * 2, false);
ctx.fillStyle = "yellow";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(1600, 460, 15, 0, Math.PI * 2, false);
ctx.fillStyle = "blue";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(1605, 515, 15, 0, Math.PI * 2, false);
ctx.fillStyle = "green";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(1658, 545, 15, 0, Math.PI * 2, false);
ctx.fillStyle = "orange";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//face
ctx.beginPath();
ctx.arc(1550, 650, 130, 0, Math.PI * 2, false);
ctx.fillStyle = "gold";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//cheeks
ctx.beginPath();
ctx.arc(1460, 650, 20, 0, Math.PI * 2, false);
ctx.fillStyle = "lightPink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(1645, 650, 20, 0, Math.PI * 2, false);
ctx.fillStyle = "lightPink";
ctx.fill();
ctx.lineWidth = 1;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//smile
ctx.beginPath();
ctx.bezierCurveTo(1490, 690, 1550, 760, 1610, 690);
ctx.lineWidth = 3;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
//eyes
ctx.beginPath();
ctx.bezierCurveTo(1480, 605, 1505, 570, 1540, 605);
ctx.lineWidth = 3;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(1570, 605, 1595, 570, 1630, 605);
ctx.lineWidth = 3;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//party blower
ctx.beginPath();
ctx.arc(540, 770, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(590, 795, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.arc(580, 790, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.arc(570, 785, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.arc(560, 780, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.arc(550, 775, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.arc(600, 800, 50, 0, Math.PI * 2, false);
ctx.fillStyle = "silver";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(630, 760);
ctx.lineTo(550, 720);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(580, 845);
ctx.lineTo(520, 815);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(505, 810);
ctx.lineTo(350, 860);
ctx.lineTo(380, 890);
ctx.lineTo(590, 850);
ctx.fillStyle = "silver";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.moveTo(350, 860);
ctx.lineTo(300, 875);
ctx.lineTo(320, 905);
ctx.lineTo(380, 890);
ctx.fillStyle = "red";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(605, 820, 630, 805, 610, 790);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(585, 785, 570, 815, 605, 820);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(630, 785, 610, 750, 585, 785);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(610, 850, 650, 820, 630, 785);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//party popper
ctx.beginPath();
ctx.ellipse(1220, 345, 50, 20, Math.PI / 5, 0, Math.PI * 2);
ctx.fillStyle = "red";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(1142, 288, 70, 50, Math.PI / 5, 0, Math.PI * 2);
ctx.fillStyle = "red";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.bezierCurveTo(1260, 375, 1250, 400, 1230, 420);
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.ellipse(1100, 260, 30, 20, Math.PI / 1.5, 0, Math.PI * 2);
ctx.fillStyle = "grey";
ctx.fill();
ctx.lineWidth = 2;
ctx.strokeStyle = "black";
ctx.stroke();
ctx.closePath();

//message
ctx.beginPath();
ctx.font = "90px Comic Sans MS";
ctx.fillStyle = "black";
ctx.fillText("Happy", 500, 170);
ctx.closePath();
ctx.beginPath();
ctx.font = "90px Comic Sans MS";
ctx.fillStyle = "black";
ctx.fillText("Birthday", 1000, 890);
ctx.closePath();
